<?php

namespace srag\Plugins\TPMS\Config;

use srag\Plugins\TPMS\Utils\TPMSTrait;
use ilTPMSConfigGUI;
use ilTPMSPlugin;
use srag\ActiveRecordConfig\TPMS\Config\AbstractFactory;

/**
 * Class Factory
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\TPMS\Config
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Factory extends AbstractFactory
{

    use TPMSTrait;
    const PLUGIN_CLASS_NAME = ilTPMSPlugin::class;
    /**
     * @var self
     */
    protected static $instance = null;


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * Factory constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }


    /**
     * @param ilTPMSConfigGUI $parent
     *
     * @return ConfigFormGUI
     */
    public function newFormInstance(ilTPMSConfigGUI $parent) : ConfigFormGUI
    {
        $form = new ConfigFormGUI($parent);

        return $form;
    }
}
