<?php

namespace srag\Plugins\TPMS\Config;

use srag\Plugins\TPMS\Utils\TPMSTrait;
use ilTPMSPlugin;
use srag\ActiveRecordConfig\TPMS\Config\AbstractFactory;
use srag\ActiveRecordConfig\TPMS\Config\AbstractRepository;
use srag\ActiveRecordConfig\TPMS\Config\Config;
use srag\Plugins\TPMS\Exception\TPMSException;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\TPMS\Config
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Repository extends AbstractRepository
{

    use TPMSTrait;
    const PLUGIN_CLASS_NAME = ilTPMSPlugin::class;
    /**
     * @var self
     */
    protected static $instance = null;


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * Repository constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }


    /**
     * @inheritDoc
     *
     * @return Factory
     */
    public function factory() : AbstractFactory
    {
        return Factory::getInstance();
    }

    /**
     * @return string
     * @throws TPMSException
     */
    public function getUrl() : string
    {
        $url = $this->getValue(ConfigFormGUI::KEY_URL);
        if (!$url) {
            throw new TPMSException('please define an URL in the plugin configuration');
        }
        return $url;
    }


    /**
     * @inheritDoc
     */
    protected function getTableName() : string
    {
        return ilTPMSPlugin::PLUGIN_ID . "_config";
    }

    /**
     * @inheritDoc
     */
    protected function getFields() : array
    {
        return [
            ConfigFormGUI::KEY_URL => Config::TYPE_STRING
        ];
    }
}
