<?php

namespace srag\Plugins\TPMS\Utils;

use srag\Plugins\TPMS\Repository;

/**
 * Trait TPMSTrait
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\TPMS\Utils
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
trait TPMSTrait
{

    /**
     * @return Repository
     */
    protected static function TPMS() : Repository
    {
        return Repository::getInstance();
    }
}
